### PR TITLE
Build on OSx

### PR DESCRIPTION
**Pull request by xvw**
I have try to launch the project on my Macbook. 
Mono doesn't work with framework .NET 4.5.2 so I change it for 4.5, I think it doesn't broke anything? 
After, "//" as a separator is only for Window. I used "System.IO.Path.Combine" to concat filepath. 
After compilation, the project seems work (with a little graphical bug on the DisplayDemoTip... the window is too small :'( ). 
When I create a Project, the current version of the editor "close", is that normal? 

I'm really sorry for my very ugly english ;)

### CODE REVIEW

**Comment by Wano-k** [comment]
I don't think that you should run this on OSX, this repository is only for Windows. It's using winforms that is making the widgets ugly and sometimes not working well on Linux, I guess it's the same result for OSX. I've already made another repository for Linux using GTK# which is remplacing winforms, you should try to launch the project on your Mac with this one ! https://github.com/Wano-k/RPG-Paper-Maker-for-Linux

**Comment by xvw** [comment]
Oké ! 
(But the usage of Path.Combine seems better than concat ;) )

**Comment by xvw** [comment]
(In fact, you should merge this PR ...)

**Comment by Wano-k** [comment]
You are right for paths, I set that ugly stuff. However I didn't set the .NET framework version, I don't have any problem on all PC where I tried.

**Pull request closed without merging**
